services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SERVER_PORT: 8080
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MANAGEMENT_SERVER_PORT: 8080
      MANAGEMENT_ENDPOINTS_WEB_BASE_PATH: /actuator
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: never
    expose:
      - "8080"       # ← 컨테이너 간 통신만 필요하면 expose만
    # ports:
    #   - "8080:8080" # 호스트로도 열고 싶을 때만

  certgen:
    image: alpine:3.20
    volumes:
      - ./certs:/out:rw
    command: >
      sh -c "
      apk add --no-cache openssl >/dev/null 2>&1;
      [ -f /out/dev.key ] || openssl req -x509 -newkey rsa:2048 -nodes -days 825
      -subj '/CN=dev-naver.i4624.info'
      -addext 'subjectAltName=DNS:dev-naver.i4624.info,DNS:gs-main-api.i4624.info,IP:127.0.0.1'
      -keyout /out/dev.key -out /out/dev.crt
      "

  proxy:
    image: nginx:alpine
    depends_on:
      certgen:
        condition: service_completed_successfully
      app:
        condition: service_started
    ports:
      - "443:443"    # ← 추가
      - "8443:8443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./certs:/etc/ssl/local:ro   # ← 인증서는 읽기 전용이면 충분
    command: ["nginx", "-g", "daemon off;"]
