services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8080
    expose:
      - "8080"
    # 개발 중 내부 확인용: 원하면 열어두기
    # ports:
    #   - "8080:8080"

  proxy:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/ssl/local:rw
    # certs가 없으면 부팅시 1회성 self-signed 자동 생성 → 실행만 해도 https OK
    command: >
      sh -c "
      [ -f /etc/ssl/local/dev.key ] || openssl req -x509 -newkey rsa:2048 -nodes -days 365
        -subj '/CN=dev-naver.i4624.info'
        -keyout /etc/ssl/local/dev.key
        -out /etc/ssl/local/dev.crt;
      nginx -g 'daemon off;'"
